package com.eyyg.auralsphere.utils

import android.os.Bundle
import com.eyyg.auralsphere.data.model.Playlist
import com.eyyg.auralsphere.data.model.Track

object FakeDataGenerator {
    val genreColors = listOf(
        "#00C513",
        "#C33D13",
        "#FF3D00",
        "#DD0000",
        "#13123A",
        "#58569F",
        "#FD8282",
        "#003A06",
        "#A59500",
        "#740068",
        "#30192D",
        "#808080",
        "#008C77",
    )

    val history: MutableList<Bundle> = mutableListOf()

    fun getPlaylists(): List<Playlist> {
        return listOf(
            Playlist("first playlist name"),
            Playlist("name of the second"),
            Playlist("that's third")
        )
    }

    fun getGenres(): List<String> {
        return listOf(
            "acoustic",
            "rock",
            "folk",
            "singer-songwriter",
            "songwriter",
            "piano",
            "blues",
            "j-rock",
            "jazz",
            "british",
            "guitar",
            "afrobeat",
            "dub",
            "alt-rock",
            "alternative",
            "hard-rock",
            "metal",
            "turkish",
            "industrial",
            "grunge",
            "emo",
            "power-pop",
            "punk-rock",
            "punk",
            "hardcore",
            "latin",
            "ska",
            "garage",
            "psych-rock",
            "brazil",
            "mpb",
            "r-n-b",
            "groove",
            "funk",
            "electronic",
            "chill",
            "electro",
            "house",
            "soul",
            "swedish",
            "trip-hop",
            "indie-pop",
            "ambient",
            "indie",
            "classical",
            "world-music",
            "black-metal",
            "new-age",
            "anime",
            "j-pop",
            "death-metal",
            "goth",
            "opera",
            "metalcore",
            "bluegrass",
            "comedy",
            "rock-n-roll",
            "rockabilly",
            "country",
            "gospel",
            "reggae",
            "samba",
            "breakbeat",
            "children",
            "cantopop",
            "mandopop",
            "chicago-house",
            "detroit-techno",
            "sad",
            "german",
            "french",
            "club",
            "dance",
            "pop",
            "edm",
            "hip-hop",
            "trance",
            "dancehall",
            "j-dance",
            "deep-house",
            "minimal-techno",
            "techno",
            "disco",
            "synth-pop",
            "party",
            "disney",
            "drum-and-bass",
            "dubstep",
            "indian",
            "progressive-house",
            "latino",
            "sertanejo",
            "forro",
            "pagode",
            "grindcore",
            "happy",
            "hardstyle",
            "heavy-metal",
            "reggaeton",
            "k-pop",
            "malay",
            "honky-tonk",
            "idm",
            "iranian",
            "j-idol",
            "pop-film",
            "kids",
            "show-tunes",
            "romance",
            "salsa",
            "sleep",
            "spanish",
            "study",
            "tango"
        )
    }
}